# Generated by Django 4.2.1 on 2023-05-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='Follower',
            new_name='follower',
        ),
    ]
